id = "mountain-theme"
name = "Mountain"
version = "0.0.1"
schema_version = 1
authors = ["xproklyatx"]
description = "Port of Mountain theme for Zed Editor"
repository = "https://github.com/xproklyatx/mountain-zed"
