id = "mountain-zed"
name = "Mountain"
version = "0.0.1"
schema_version = 1
authors = ["xproklyatx"]
description = "Port of Mountain theme for Zed Edittor"
repository = "https://github.com/xproklyatx/mountain-zed"
